[package]
name = "rust-chaos"
version = "0.1.0"
authors = ["james.anderson <jwanderson117@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.16.0"
rand = "0.8.3"
arr_macro = "0.1.3"
